# Spark .NET build

trigger:
  batch: true
  branches:
    include:
    - master

variables:
  buildConfiguration: 'Release'
  _SignType: real
  _TeamName: DotNetSpark

  # Azure DevOps variables are transformed into environment variables, with these variables we
  # avoid the first time experience and telemetry to speed up the build.
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

  # Maven Cache
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)\.m2\repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

jobs:
- job: Build
  displayName: Build and Test Sources
  pool: Hosted VS2017

  variables:
    ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
      _OfficialBuildIdArgs: /p:OfficialBuildId=$(BUILD.BUILDNUMBER)

  steps:
  - script: mkdir $(Pipeline.Workspace)\.m2
  - script: cmdkey /add:aerox.file.core.windows.net /user:Azure\aerox /pass:$(STORAGEKEY)
  - script: mklink /d "$(MAVEN_CACHE_FOLDER)" "\\aerox.file.core.windows.net\spark-maven\"

  - task: Maven@3
    displayName: 'Maven build src'
    inputs:
      mavenPomFile: src/scala/pom.xml
      mavenOptions: $(MAVEN_OPTS)

  - task: Maven@3
    displayName: 'Maven build benchmark'
    inputs:
      mavenPomFile: benchmark/scala/pom.xml
      mavenOptions: $(MAVEN_OPTS)

  - task: BatchScript@1
    displayName: Download Spark Distros & Winutils.exe
    inputs:
      filename: script\download-spark-distros.cmd
      arguments: $(Build.BinariesDirectory)

  - script: build.cmd -pack
              -c $(buildConfiguration)
              -ci
              $(_OfficialBuildIdArgs)
              /p:PublishSparkWorker=true
              /p:SparkWorkerPublishDir=$(Build.ArtifactStagingDirectory)\Microsoft.Spark.Worker
    displayName: '.NET build'

  - task: DotNetCoreCLI@2
    displayName: '.NET unit tests'
    inputs:
      command: test
      projects: '**/*UnitTest/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: CopyFiles@2
    displayName: Stage .NET artifacts
    inputs:
      sourceFolder: $(Build.SourcesDirectory)/artifacts/packages/$(buildConfiguration)/Shipping
      contents: |
        **/*.nupkg
        **/*.snupkg
      targetFolder: $(Build.ArtifactStagingDirectory)/BuildArtifacts/artifacts/packages/$(buildConfiguration)/Shipping

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName:  Microsoft.Spark.Binaries
